### ISSUE TITLE
 "Unknown exception while processing file"

### ISSUE THREAD

**Issue by concon** [openMLA/linear-shaft-motor#1]
I get this error when I try to open it in FreeCAD, what might be the reason?

Unknown exception while processing file: C:/Users/lemi/Downloads/linear-shaft-motor-main/linear-shaft-motor-main/components/linear-shaft-motor-assembly.FCStd

**Comment by NemoAndrea** [comment]
This is because the binary files are managed through [git-annex](https://git-annex.branchable.com/). I realised I had not pushed the annex branch so that makes it a bit difficult. I have not made the remote annex storage (google cloud in my case) available yet, so you cannot fetch the files atm. Until you download the file, the file in the main repo structure is just a [symlink](https://en.wikipedia.org/wiki/Symbolic_link) that points to a non-existing file.

Will set that up if I find some time this week. Do note that the current project is very unfinished so I doubt you get much out of it in the current state. For the openMLA project the current day to day work is on the optics so the stage is a bit on hold.

**Comment by NemoAndrea** [comment]
Alright, that is all sorted now. you can now clone the repository and (assuming you have git-annex installed) run 
```shell
git annex get .
```
Note that you will need to have pulled the latest version of the git-annex branch] https://github.com/openMLA/linear-shaft-motor/commit/09415f2a7f0d5487c3d07e2c3810a101a7b6c7a3 (updated just now).
